rs_queue:
    server:
        redis:
            host: redis

apisearch_server:
    middleware_domain_events_service: apisearch_server.middleware.ignore_events
    middleware_logs_service: apisearch_server.middleware.ignore_logs
    cluster:
        docker_elasticsearch_service:
            host: elasticsearch
            port: 9200
